apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-asya
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-asya
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-asya
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-asya
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-asya
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-crnp-tenant/rhtap-demo-app/hacbs-test-project-asya@sha256:41761b82b3eb51fdc82ec024d965908dec4706abdfe58d5d8871acc6f64affdb
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
